from abc import ABC, abstractmethod


class ServiceHandler(ABC):
    """
    An abstract base class for managing bot services. Subclasses are expected to implement
    specific methods for loading services, choosing a service based on user input, and generating responses.
    """

    @abstractmethod
    def choose_service(self, user_message: str) -> str:
        """
        Abstract method to choose a service from available options based on the user's message.
        
        Parameters:
            user_message (str): The input message from the user.

        Returns:
            str: The chosen service identifier.
        """
        pass

    @abstractmethod
    def get_response(self, user_message: str, location: str, region_id: int) -> str:
        """
        Generates a response based on user input, location, and region-specific service data.

        Parameters:
            user_message (str): The message input from the user, guiding the response content.
            location (str): The user's geographic location, used to refine service filtering.
            region_id (int): The specified region id to determine regional service context.

        Returns:
            str: A customized response string generated by the bot based on the provided parameters.
        """
        pass
